
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.system_v8_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-21T12:56:13.080-04:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "SystemService",
                      portName = "SystemInfoPort",
                      targetNamespace = "http://www.travelport.com/service/system_v8_0",
                      wsdlLocation = "file:/Users/pedroboza/eclipse-workspace/Travelport Tutorial/wsdl/system_v8_0/System.wsdl",
                      endpointInterface = "com.travelport.service.system_v8_0.SystemInfoPortType")
                      
public class SystemInfoPortImpl implements SystemInfoPortType {

    private static final Logger LOG = Logger.getLogger(SystemInfoPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.system_v8_0.SystemInfoPortType#service(com.travelport.schema.system_v8_0.SystemInfoReq  parameters )*
     */
    public com.travelport.schema.system_v8_0.SystemInfoRsp service(com.travelport.schema.system_v8_0.SystemInfoReq parameters) throws SystemFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.system_v8_0.SystemInfoRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SystemFaultMessage("SystemFaultMessage...");
    }

}
