
package com.travelport.service.universal_v27_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-21T16:08:16.823-04:00
 * Generated source version: 3.0.0
 */

@WebFault(name = "ErrorInfo", targetNamespace = "http://www.travelport.com/schema/common_v27_0")
public class RailFaultMessage extends Exception {
    
    private com.travelport.schema.common_v27_0.ErrorInfo errorInfo;

    public RailFaultMessage() {
        super();
    }
    
    public RailFaultMessage(String message) {
        super(message);
    }
    
    public RailFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public RailFaultMessage(String message, com.travelport.schema.common_v27_0.ErrorInfo errorInfo) {
        super(message);
        this.errorInfo = errorInfo;
    }

    public RailFaultMessage(String message, com.travelport.schema.common_v27_0.ErrorInfo errorInfo, Throwable cause) {
        super(message, cause);
        this.errorInfo = errorInfo;
    }

    public com.travelport.schema.common_v27_0.ErrorInfo getFaultInfo() {
        return this.errorInfo;
    }
}
