
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.travelport.service.hotel_v27_0;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.0
 * 2014-06-21T13:10:40.930-04:00
 * Generated source version: 3.0.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "HotelService",
                      portName = "HotelDetailsServicePort",
                      targetNamespace = "http://www.travelport.com/service/hotel_v27_0",
                      wsdlLocation = "file:/Users/pedroboza/eclipse-workspace/Travelport Tutorial/wsdl/hotel_v27_0/Hotel.wsdl",
                      endpointInterface = "com.travelport.service.hotel_v27_0.HotelDetailsServicePortType")
                      
public class HotelDetailsServicePortImpl implements HotelDetailsServicePortType {

    private static final Logger LOG = Logger.getLogger(HotelDetailsServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.travelport.service.hotel_v27_0.HotelDetailsServicePortType#service(com.travelport.schema.hotel_v27_0.HotelDetailsReq  parameters )*
     */
    public com.travelport.schema.hotel_v27_0.HotelDetailsRsp service(com.travelport.schema.hotel_v27_0.HotelDetailsReq parameters) throws HotelFaultMessage    { 
        LOG.info("Executing operation service");
        System.out.println(parameters);
        try {
            com.travelport.schema.hotel_v27_0.HotelDetailsRsp _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new HotelFaultMessage("HotelFaultMessage...");
    }

}
